/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginSelectionRouteImport } from './routes/login-selection'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginUserRouteImport } from './routes/login/user'
import { Route as LoginAdminRouteImport } from './routes/login/admin'
import { Route as LibraryRecentRouteImport } from './routes/library/recent'
import { Route as LibraryLikedRouteImport } from './routes/library/liked'
import { Route as CategoryNameRouteImport } from './routes/category.$name'
import { Route as AdminUploadRouteImport } from './routes/admin/upload'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginSelectionRoute = LoginSelectionRouteImport.update({
  id: '/login-selection',
  path: '/login-selection',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginUserRoute = LoginUserRouteImport.update({
  id: '/login/user',
  path: '/login/user',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginAdminRoute = LoginAdminRouteImport.update({
  id: '/login/admin',
  path: '/login/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRecentRoute = LibraryRecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => LibraryRoute,
} as any)
const LibraryLikedRoute = LibraryLikedRouteImport.update({
  id: '/liked',
  path: '/liked',
  getParentRoute: () => LibraryRoute,
} as any)
const CategoryNameRoute = CategoryNameRouteImport.update({
  id: '/category/$name',
  path: '/category/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUploadRoute = AdminUploadRouteImport.update({
  id: '/admin/upload',
  path: '/admin/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRoute
  '/home': typeof HomeRoute
  '/library': typeof LibraryRouteWithChildren
  '/login-selection': typeof LoginSelectionRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/upload': typeof AdminUploadRoute
  '/category/$name': typeof CategoryNameRoute
  '/library/liked': typeof LibraryLikedRoute
  '/library/recent': typeof LibraryRecentRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/user': typeof LoginUserRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRoute
  '/home': typeof HomeRoute
  '/library': typeof LibraryRouteWithChildren
  '/login-selection': typeof LoginSelectionRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/upload': typeof AdminUploadRoute
  '/category/$name': typeof CategoryNameRoute
  '/library/liked': typeof LibraryLikedRoute
  '/library/recent': typeof LibraryRecentRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/user': typeof LoginUserRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRoute
  '/home': typeof HomeRoute
  '/library': typeof LibraryRouteWithChildren
  '/login-selection': typeof LoginSelectionRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/upload': typeof AdminUploadRoute
  '/category/$name': typeof CategoryNameRoute
  '/library/liked': typeof LibraryLikedRoute
  '/library/recent': typeof LibraryRecentRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/user': typeof LoginUserRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/downloads'
    | '/home'
    | '/library'
    | '/login-selection'
    | '/onboarding'
    | '/profile'
    | '/search'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/upload'
    | '/category/$name'
    | '/library/liked'
    | '/library/recent'
    | '/login/admin'
    | '/login/user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/downloads'
    | '/home'
    | '/library'
    | '/login-selection'
    | '/onboarding'
    | '/profile'
    | '/search'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/upload'
    | '/category/$name'
    | '/library/liked'
    | '/library/recent'
    | '/login/admin'
    | '/login/user'
  id:
    | '__root__'
    | '/'
    | '/downloads'
    | '/home'
    | '/library'
    | '/login-selection'
    | '/onboarding'
    | '/profile'
    | '/search'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/upload'
    | '/category/$name'
    | '/library/liked'
    | '/library/recent'
    | '/login/admin'
    | '/login/user'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DownloadsRoute: typeof DownloadsRoute
  HomeRoute: typeof HomeRoute
  LibraryRoute: typeof LibraryRouteWithChildren
  LoginSelectionRoute: typeof LoginSelectionRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminUploadRoute: typeof AdminUploadRoute
  CategoryNameRoute: typeof CategoryNameRoute
  LoginAdminRoute: typeof LoginAdminRoute
  LoginUserRoute: typeof LoginUserRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-selection': {
      id: '/login-selection'
      path: '/login-selection'
      fullPath: '/login-selection'
      preLoaderRoute: typeof LoginSelectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/user': {
      id: '/login/user'
      path: '/login/user'
      fullPath: '/login/user'
      preLoaderRoute: typeof LoginUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/admin': {
      id: '/login/admin'
      path: '/login/admin'
      fullPath: '/login/admin'
      preLoaderRoute: typeof LoginAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/recent': {
      id: '/library/recent'
      path: '/recent'
      fullPath: '/library/recent'
      preLoaderRoute: typeof LibraryRecentRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/library/liked': {
      id: '/library/liked'
      path: '/liked'
      fullPath: '/library/liked'
      preLoaderRoute: typeof LibraryLikedRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/category/$name': {
      id: '/category/$name'
      path: '/category/$name'
      fullPath: '/category/$name'
      preLoaderRoute: typeof CategoryNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/upload': {
      id: '/admin/upload'
      path: '/admin/upload'
      fullPath: '/admin/upload'
      preLoaderRoute: typeof AdminUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LibraryRouteChildren {
  LibraryLikedRoute: typeof LibraryLikedRoute
  LibraryRecentRoute: typeof LibraryRecentRoute
}

const LibraryRouteChildren: LibraryRouteChildren = {
  LibraryLikedRoute: LibraryLikedRoute,
  LibraryRecentRoute: LibraryRecentRoute,
}

const LibraryRouteWithChildren =
  LibraryRoute._addFileChildren(LibraryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DownloadsRoute: DownloadsRoute,
  HomeRoute: HomeRoute,
  LibraryRoute: LibraryRouteWithChildren,
  LoginSelectionRoute: LoginSelectionRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminUploadRoute: AdminUploadRoute,
  CategoryNameRoute: CategoryNameRoute,
  LoginAdminRoute: LoginAdminRoute,
  LoginUserRoute: LoginUserRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
